# Generated by Django 2.2.5 on 2021-04-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0004_auto_20210421_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='key_words',
            new_name='keywords',
        ),
    ]
