# Generated by Django 2.2.5 on 2021-04-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0005_auto_20210421_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='collaborative_recommendations',
        ),
    ]
