# Generated by Django 2.2.5 on 2021-04-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0006_auto_20210426_1704'),
        ('movie_service', '0006_remove_movie_collaborative_recommendations'),
    ]

    operations = [
    ]
